### ISSUE TITLE
installtion issue 

### ISSUE THREAD

**Issue by invisiblecoder99** [godka/kurento-rtmp#1]
npm issues please update your code

**Comment by invisiblecoder99** [comment]
finally installed but struck on this step

Page loaded ...
Starting video call ...
Creating WebRtcPeer and generating local sdp offer ...
spec:   {"audio":true,"video":{"width":640,"framerate":15}}
chrome: {"audio":true,"video":{"optional":[{"minWidth":640},{"maxWidth":640},{"minFramerate":15},{"maxFramerate":15}]}}
Invoking SDP offer callback function 74.207.250.151:8443
Senging message: {"id":"start","sdpOffer":"v=0\r\no=- 2653098187878006014 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE audio video\r\na=msid-semantic: WMS wdhF7O4i2CW3ExVWjdytXDzPCfxADvKlvNrE\r\nm=audio 65108 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126\r\nc=IN IP4 172.20.10.3\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=candidate:2871749022 1 udp 2113937151 172.20.10.3 65108 typ host generation 0 network-cost 50\r\na=candidate:4109229315 1 udp 2113932031 2001::9d38:953c:3021:d911:346f:a223 65109 typ host generation 0 network-cost 50\r\na=ice-ufrag:U0dy\r\na=ice-pwd:Q0cKVw/FY4tmUgPqIuy3cFM0\r\na=ice-options:trickle\r\na=fingerprint:sha-256 72:CA:FF:4B:23:B1:F8:00:32:01:11:6C:24:D8:CE:1E:25:73:1F:0F:B5:12:1C:6C:3D:B0:E4:ED:10:8A:DE:A1\r\na=setup:actpass\r\na=mid:audio\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=sendrecv\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtpmap:103 ISAC/16000\r\na=rtpmap:104 ISAC/32000\r\na=rtpmap:9 G722/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:106 CN/32000\r\na=rtpmap:105 CN/16000\r\na=rtpmap:13 CN/8000\r\na=rtpmap:110 telephone-event/48000\r\na=rtpmap:112 telephone-event/32000\r\na=rtpmap:113 telephone-event/16000\r\na=rtpmap:126 telephone-event/8000\r\na=ssrc:1646473433 cname:vt1tPcU+Cx9dz+mZ\r\na=ssrc:1646473433 msid:wdhF7O4i2CW3ExVWjdytXDzPCfxADvKlvNrE 09d499e4-5ca5-40b8-8bad-0e497f3948b0\r\na=ssrc:1646473433 mslabel:wdhF7O4i2CW3ExVWjdytXDzPCfxADvKlvNrE\r\na=ssrc:1646473433 label:09d499e4-5ca5-40b8-8bad-0e497f3948b0\r\nm=video 65110 UDP/TLS/RTP/SAVPF 96 98 100 102 127 97 99 101 125\r\nc=IN IP4 172.20.10.3\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=candidate:2871749022 1 udp 2113937151 172.20.10.3 65110 typ host generation 0 network-cost 50\r\na=candidate:4109229315 1 udp 2113932031 2001::9d38:953c:3021:d911:346f:a223 65111 typ host generation 0 network-cost 50\r\na=ice-ufrag:U0dy\r\na=ice-pwd:Q0cKVw/FY4tmUgPqIuy3cFM0\r\na=ice-options:trickle\r\na=fingerprint:sha-256 72:CA:FF:4B:23:B1:F8:00:32:01:11:6C:24:D8:CE:1E:25:73:1F:0F:B5:12:1C:6C:3D:B0:E4:ED:10:8A:DE:A1\r\na=setup:actpass\r\na=mid:video\r\na=extmap:2 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:4 urn:3gpp:video-orientation\r\na=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=sendrecv\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:96 VP8/90000\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtcp-fb:96 goog-remb\r\na=rtcp-fb:96 transport-cc\r\na=rtpmap:98 VP9/90000\r\na=rtcp-fb:98 ccm fir\r\na=rtcp-fb:98 nack\r\na=rtcp-fb:98 nack pli\r\na=rtcp-fb:98 goog-remb\r\na=rtcp-fb:98 transport-cc\r\na=rtpmap:100 H264/90000\r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 nack pli\r\na=rtcp-fb:100 goog-remb\r\na=rtcp-fb:100 transport-cc\r\na=fmtp:100 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\na=rtpmap:102 red/90000\r\na=rtpmap:127 ulpfec/90000\r\na=rtpmap:97 rtx/90000\r\na=fmtp:97 apt=96\r\na=rtpmap:99 rtx/90000\r\na=fmtp:99 apt=98\r\na=rtpmap:101 rtx/90000\r\na=fmtp:101 apt=100\r\na=rtpmap:125 rtx/90000\r\na=fmtp:125 apt=102\r\na=ssrc-group:FID 2198468124 2236330452\r\na=ssrc:2198468124 cname:vt1tPcU+Cx9dz+mZ\r\na=ssrc:2198468124 msid:wdhF7O4i2CW3ExVWjdytXDzPCfxADvKlvNrE 5c30ed25-bfcf-4260-b483-d2f474d1c7ed\r\na=ssrc:2198468124 mslabel:wdhF7O4i2CW3ExVWjdytXDzPCfxADvKlvNrE\r\na=ssrc:2198468124 label:5c30ed25-bfcf-4260-b483-d2f474d1c7ed\r\na=ssrc:2236330452 cname:vt1tPcU+Cx9dz+mZ\r\na=ssrc:2236330452 msid:wdhF7O4i2CW3ExVWjdytXDzPCfxADvKlvNrE 5c30ed25-bfcf-4260-b483-d2f474d1c7ed\r\na=ssrc:2236330452 mslabel:wdhF7O4i2CW3ExVWjdytXDzPCfxADvKlvNrE\r\na=ssrc:2236330452 label:5c30ed25-bfcf-4260-b483-d2f474d1c7ed\r\n"}
Local candidate{"candidate":"candidate:2871749022 1 udp 2113937151 172.20.10.3 65108 typ host generation 0 ufrag U0dy network-cost 50","sdpMid":"audio","sdpMLineIndex":0}
Senging message: {"id":"onIceCandidate","candidate":{"candidate":"candidate:2871749022 1 udp 2113937151 172.20.10.3 65108 typ host generation 0 ufrag U0dy network-cost 50","sdpMid":"audio","sdpMLineIndex":0}}
Local candidate{"candidate":"candidate:4109229315 1 udp 2113932031 2001::9d38:953c:3021:d911:346f:a223 65109 typ host generation 0 ufrag U0dy network-cost 50","sdpMid":"audio","sdpMLineIndex":0}
Senging message: {"id":"onIceCandidate","candidate":{"candidate":"candidate:4109229315 1 udp 2113932031 2001::9d38:953c:3021:d911:346f:a223 65109 typ host generation 0 ufrag U0dy network-cost 50","sdpMid":"audio","sdpMLineIndex":0}}
Local candidate{"candidate":"candidate:2871749022 1 udp 2113937151 172.20.10.3 65110 typ host generation 0 ufrag U0dy network-cost 50","sdpMid":"video","sdpMLineIndex":1}
Senging message: {"id":"onIceCandidate","candidate":{"candidate":"candidate:2871749022 1 udp 2113937151 172.20.10.3 65110 typ host generation 0 ufrag U0dy network-cost 50","sdpMid":"video","sdpMLineIndex":1}}
Local candidate{"candidate":"candidate:4109229315 1 udp 2113932031 2001::9d38:953c:3021:d911:346f:a223 65111 typ host generation 0 ufrag U0dy network-cost 50","sdpMid":"video","sdpMLineIndex":1}
Senging message: {"id":"onIceCandidate","candidate":{"candidate":"candidate:4109229315 1 udp 2113932031 2001::9d38:953c:3021:d911:346f:a223 65111 typ host generation 0 ufrag U0dy network-cost 50","sdpMid":"video","sdpMLineIndex":1}}
Local candidate{"candidate":"candidate:842163049 1 udp 1677729535 203.144.93.220 26152 typ srflx raddr 172.20.10.3 rport 65108 generation 0 ufrag U0dy network-cost 50","sdpMid":"audio","sdpMLineIndex":0}
Senging message: {"id":"onIceCandidate","candidate":{"candidate":"candidate:842163049 1 udp 1677729535 203.144.93.220 26152 typ srflx raddr 172.20.10.3 rport 65108 generation 0 ufrag U0dy network-cost 50","sdpMid":"audio","sdpMLineIndex":0}}
Local candidate{"candidate":"candidate:842163049 1 udp 1677729535 203.144.93.220 26153 typ srflx raddr 172.20.10.3 rport 65110 generation 0 ufrag U0dy network-cost 50","sdpMid":"video","sdpMLineIndex":1}
Senging message: {"id":"onIceCandidate","candidate":{"candidate":"candidate:842163049 1 udp 1677729535 203.144.93.220 26153 typ srflx raddr 172.20.10.3 rport 65110 generation 0 ufrag U0dy network-cost 50","sdpMid":"video","sdpMLineIndex":1}}

**Comment by invisiblecoder99** [comment]
on node console 

root@localhost:~/kurento-rtmp# node server.js
Kurento Tutorial started
Open https://localhost:8443/ with a WebRTC capable browser
Node Media Rtmp Server started on port: 1935
Node Media Http Server started on port: 8000
Node Media WebSocket Server started on port: 8000
Connection received with sessionId MFS5kpXPnw4azLLo-q9pipxT8sS1xA0q
TypeError: Cannot read property 'unmask' of undefined
    at Receiver.unmask (/root/kurento-rtmp/node_modules/ws/lib/Receiver.js:294:46)
    at Receiver.finish (/root/kurento-rtmp/node_modules/ws/lib/Receiver.js:463:25)
    at Receiver.expectHandler (/root/kurento-rtmp/node_modules/ws/lib/Receiver.js:451:33)
    at Receiver.add (/root/kurento-rtmp/node_modules/ws/lib/Receiver.js:95:24)
    at TLSSocket.realHandler (/root/kurento-rtmp/node_modules/ws/lib/WebSocket.js:800:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at TLSSocket.Readable.push (_stream_readable.js:136:10)
    at TLSWrap.onread (net.js:561:20)
Connection MFS5kpXPnw4azLLo-q9pipxT8sS1xA0q closed
Connection received with sessionId FwGegqJit5Nd-iJfov-eHvdB4xSak4rT
TypeError: Cannot read property 'unmask' of undefined
    at Receiver.unmask (/root/kurento-rtmp/node_modules/ws/lib/Receiver.js:294:46)
    at Receiver.finish (/root/kurento-rtmp/node_modules/ws/lib/Receiver.js:463:25)
    at Receiver.expectHandler (/root/kurento-rtmp/node_modules/ws/lib/Receiver.js:451:33)
    at Receiver.add (/root/kurento-rtmp/node_modules/ws/lib/Receiver.js:95:24)
    at TLSSocket.realHandler (/root/kurento-rtmp/node_modules/ws/lib/WebSocket.js:800:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at TLSSocket.Readable.push (_stream_readable.js:136:10)
    at TLSWrap.onread (net.js:561:20)

**Comment by invisiblecoder99** [comment]
solved  use bufferutil@1 and utf-8-validate@2.

**Comment by invisiblecoder99** [comment]
finally i want to remove nodemedia server from it and also want to know weather it support multiple sessions at same time  now it is working fine

**Comment by invisiblecoder99** [comment]
could you separate publish page and viewer page separately possibly separate servers and let me know

**Comment by invisiblecoder99** [comment]
provide your skype i want to talk with you

**Comment by invisiblecoder99** [comment]
![image](https://user-images.githubusercontent.com/6527923/31996408-9eafd1a8-b9b2-11e7-8ab4-7daec600f7fa.png)

after few seconds image turning to this whats the issue

**Comment by invisiblecoder99** [comment]
can you give me code with audio please

**Comment by invisiblecoder99** [comment]
![image](https://user-images.githubusercontent.com/6527923/32003989-ef2e156e-b9ca-11e7-82c5-338949e5ba84.png)
no audio playback but streaming getting audio after editing but no playback

**Comment by godka** [comment]
OK,I'll update my code with audio playback latter.

This demo is just like a toy,and I haven't written audio playback in SDP file. 
Currently the SDP file is shown like this:

'''
SDP:
v=0
o=- 0 0 IN IP4 127.0.0.1
s=No Name
c=IN IP4 127.0.0.1
t=0 0
a=tool:libavformat 57.71.100
m=video 55000 RTP/AVP 96
b=AS:200
a=rtpmap:96 H264/90000
'''

so the correct way to fix it will be like this:
1.add audio prop on SDP file
2.fix ffmpeg transcode script,current is 

'''
ffmpeg
-protocol_whitelist "file,udp,rtp" 
-i test.sdp 
-vcodec copy 
-f flv 
rtmp://localhost/live/stream
'''
,one should add some audio specs like '-acodec aac -strict -2'

**Comment by invisiblecoder99** [comment]
I have added audio in sdp file which is coming properly ffmpeg also showing mapping properly . But no audio in playback. Please provide me me instant messager like Skype to get in touch with you so easy to solve issues on time and save my time

**Comment by invisiblecoder99** [comment]
![image](https://user-images.githubusercontent.com/6527923/32038977-88488f8c-ba56-11e7-92fe-7863ae48e045.png)

check my sdp configuration

**Comment by invisiblecoder99** [comment]
i have  successfully adder audio i will like to push i am going to create push request please accept it

**Comment by godka** [comment]
thx

**Comment by invisiblecoder99** [comment]
add me as contributor to project i will contribute and make it stable and also i need your instant messenger contact

**Comment by invisiblecoder99** [comment]
can you help me separate viewer page ?

**Comment by invisiblecoder99** [comment]
demo running here please test 
https://portal.gopandoratv.com:8443/

**Comment by godka** [comment]
I‘m inviting you now.Sorry due to the network issue in mainland China,I can't reply your message immediately.

**Comment by invisiblecoder99** [comment]
Give me your QQ ID

**Comment by godka** [comment]
tell me your email address,or contact me from your email.
my email address is htc17@mails.tsinghua.edu.cn
