### ISSUE TITLE
not work!

### ISSUE THREAD

**Issue by WzFFzW** [godka/kurento-rtmp#10]
I copy your code, and i am already installed kurento media server and ffmpeg on my server, but is not working. I use a mp4 file to test, it work. Amazing!

ubuntu: 16.4.1
node: 8.9.1
kurento: 6.7.1

i thing some config i don't set.

My english is poor. hope your understand my mean.......
and pleace help me a lot, Itis important to me.

**Comment by WzFFzW** [comment]
你应该是中国的吧，=。=

**Comment by godka** [comment]
emmm,yes,I am Chinese...
那就直接用中文说吧，大概看明白了，主要问题是配置上的是么

**Comment by WzFFzW** [comment]
对的，感觉是的。因为客户端和服务端都是有返回sdp，ice相关的。但是服务端却接受不到任何的音频视频流
