### ISSUE TITLE
centos 上的运行问题

### ISSUE THREAD

**Issue by chaoing** [godka/kurento-rtmp#17]
您好 请问你跑demo的时候是在centos上的吗？
我在ubuntu16.04上完全没有问题
现在我在centos7.2上布了一套，kurento官网的demo都全部跑通了，说明所有的配置都是完整的

但是跑这个rtmp项目的时候出问题了， 生成的.sdp 使用ffmepeg命令推流的时候，ffmpeg报错此.sdp连接超时，并且里面没有发现视频流。

**Comment by godka** [comment]
你好
很高兴能关注我的项目。
我的服务器运行在centos上，使用yum安装的kurento。
并没有发现这类问题，有报错提示么？

祝好。

**Comment by chaoing** [comment]
已经解决了  我的sdp的ip设置有问题
