### ISSUE TITLE
Audio track present, but no sound in rtmp stream

### ISSUE THREAD

**Issue by SriramScorp** [godka/kurento-rtmp#28]
While the rtmp stream has both a video and audio track, there is no sound when I play the stream.
```
$ ffmpeg -hide_banner -i rtmp://localhost:1935/live/127.0.0.1_55002
Input #0, flv, from 'rtmp://localhost:1935/live/127.0.0.1_55002':
  Metadata:
    title           : KMS
    encoder         : Lavf58.29.100
  Duration: 00:00:00.00, start: 659.611000, bitrate: N/A
    Stream #0:0: Video: h264 (Constrained Baseline), yuv420p(progressive), 960x540, 1k tbr, 1k tbn
    Stream #0:1: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
```

**Comment by tobelyan** [comment]
i have the same issue! any solutions ?

**Comment by SriramScorp** [comment]
I was running kms version 6.13.0. Upgrading it to the current latest version (6.15.0) fixed the no audio issue.

**Comment by tobelyan** [comment]
I still have the problem, even after update
here is a topic i have opened on kurento 
https://groups.google.com/g/kurento/c/8XiI7oAOHwQ
