### ISSUE TITLE
new feature

### ISSUE THREAD

**Issue by invisiblecoder99** [godka/kurento-rtmp#3]
check this 

https://github.com/BitOfUniverse/kurento-one2many-with-rooms

creating multi-rooms on this and make it able to create room with url instead of entering in box

**Comment by invisiblecoder99** [comment]
https://stackoverflow.com/questions/31373455/socket-io-rooms-based-on-link

 check this  if you could work that would be great

**Comment by godka** [comment]
yeah, it will be really great.
Recently I'm writing a new paper via LSTM,and I have little time to deal with it.

**Comment by invisiblecoder99** [comment]
Can you give me idea to create broadcaster/id and viewer/I'd routing in server.js

**Comment by godka** [comment]
Perhaps,no.I nearly forget how to build this solution...

**Comment by invisiblecoder99** [comment]
create room feature url based then it would be easy

**Comment by invisiblecoder99** [comment]
make a form that can create custom session i mean input session name and then multiple session is implemented instead of automatic sessions

**Comment by godka** [comment]
you mean,just like kurento-room?

**Comment by invisiblecoder99** [comment]
yes but one way
