### ISSUE TITLE
Use external rtmp server

### ISSUE THREAD

**Issue by imewish** [godka/kurento-rtmp#6]
Hello,

can I use external RTMP server with this?

**Comment by invisiblecoder99** [comment]
yes you can push to external server

**Comment by imewish** [comment]
What changed I have to make in the code ? Can you guide me ?

**Comment by godka** [comment]
our scheme has contained a internal rtmp server which is written in nodejs(node-media-server),binding localhost:1935.You can remove this module to delete internal server.
a simple guide:
https://github.com/godka/kurento-rtmp/issues/5

or,you can modify rtmp push address to change server,and default rtmp url is rtmp://localhost/live/xxxxx

https://github.com/godka/kurento-rtmp/blob/b87a137fea9e2c305c5b5e17f2b77272d122a755/server.js#L357
