### ISSUE TITLE
Question: Port selection for RTP stream input to FFMPEG

### ISSUE THREAD

**Issue by t-mullen** [godka/kurento-rtmp#7]
Could you explain the choice of ports here: https://github.com/godka/kurento-rtmp/blob/master/server.js#L233

I can't seem to find any logic that would explain why the RTP stream that Kurento outputs would be on those ports.

**Comment by t-mullen** [comment]
Well I got it to work, but they are still magic numbers to me. Any explanation would help greatly.

**Comment by RationalCoding** [comment]
Also, how did you get Kurento to recognize openh264-gst-plugins-bad-1.5 for H264 support?

Simply doing `sudo apt-get install openh264-gst-plugins-bad-1.5` did not work.
