### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by DaveStein** [godka/kurento-rtmp#9]
Your test demo doesn't work. I notice that `playrtmp` expects a `rtmpaddress` to be passed, but in your markup you just run `playrtmp()` so that becomes undefined. Not sure how that is supposed to play with the swf and whatnot.

**Comment by godka** [comment]
hi. thanks for your interest.

1. rtmpaddress

I run playrtmp function with rtmpaddress here https://github.com/godka/kurento-rtmp/blob/b87a137fea9e2c305c5b5e17f2b77272d122a755/static/js/index.js#L62

2. swf support

Chrome will no longer support flash plugin till 2020. The newest chrome version doesn't open flash plugin automatically, thus, you may try to open it manually. 
https://support.google.com/chrome/answer/6258784?hl=en
I will upgrade rtmp playback module to h5 version via https://github.com/yingDev/Web-Rtmp

**Comment by DaveStein** [comment]
@godka ahhh that page is tricky for me because I see Warning in english, and the rest in Chinese. But if you could make it so RTMP is paying back without flash in your example, that would be awesome
